# Generated by Django 2.1.2 on 2018-10-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181022_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='harga_game',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='developer_game',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='genre_game',
            new_name='penerbit',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nama_game',
            new_name='pengarang',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platform_game',
        ),
    ]
